
apiVersion: v1
kind: Pod 
metadata: 
  name: newpod
  namespace: default
  labels:   
    app: newapp
spec: 
    containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort : 80
              protocol : TCP
              name: nginx
--- 
apiVersion: v1 
kind: Service
metadata:
    name: newservice
    namespace: default
spec: 
    type: NodePort
    selector: 
      app: newapp
    ports: 
        - port: 80 
          targetPort: 80
          protocol: TCP 
    
